namespace: ecadet-dev-personservice
deployment:
  image: quay.io/emm_cadet/person-service
  version: v1.0.4
  replicas: 4
  includeHealthChecks: false
postgresql:
  auth:
    database: "person-service"
    password: "postgrepasswd"
    username: "postgresuser"
    service: "person-service-postgresql"
greeting: "Hello, this is version v1.0.4"
