apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password }}
  POSTGRES_HOST: {{ .Values.postgresql.auth.service }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database }}
